### ISSUE TITLE
componente cable no se muestra cuando se arrastra (aparece un triangulo en su lugar)

### ISSUE THREAD

**Issue by YisusW** [jignaciovelazquez/grilla-react-1#19]
but on the bar is adding another figure. the red "triangulo"

![image](https://github.com/jignaciovelazquez/grilla-react-1/assets/18018741/9e1a7989-e98e-4d26-bb5f-579ad351cc72)

then resolve the potentials conflicts and then close and merge this PR as well.

there is an additional challenge here "change the red triangulo when the cable is droped or dragged"

**Comment by jignaciovelazquez** [comment]
resolved
