### ISSUE TITLE
Please enabled actions on repo

### ISSUE THREAD

**Issue by YisusW** [jignaciovelazquez/grilla-react-1#9]
look at this screen to have one referene:

![image](https://github.com/jignaciovelazquez/grilla-react-1/assets/18018741/16ebd696-caef-42fa-9217-54f0225d3813)

go there and let me know if you have any question about it.

**Comment by jignaciovelazquez** [comment]
![image](https://github.com/jignaciovelazquez/grilla-react-1/assets/108367427/70f06ad7-fcf2-4f48-9d96-c65a809e5070)

**Comment by jignaciovelazquez** [comment]
i think is activate yet

**Comment by YisusW** [comment]
yep, now it's working Thanks closing the issue.
